# donnees.py

donnees_entrainement = {
    "salutation": [
        "bonjour",
        "salut",
        "coucou",
        "hello",
        "bonsoir",
        "yo",
        "hey",
        "bonjour à tous",
        "salut tout le monde",
        "coucou la compagnie",
        "wesh",
        "ça va",
        "comment ça va",
        "comment tu vas",
        "bien ou quoi",
        "slt",
        "cc",
        "bonjour monsieur",
        "bonjour madame",
        "salutations",
        "hey there",
        "good morning",
        "aloha",
    ],
    "au_revoir": [
        "au revoir",
        "à bientôt",
        "bye",
        "je m'en vais",
        "à plus tard",
        "bonne journée",
        "bonne soirée",
        "ciao",
        "tchao",
        "à la prochaine",
        "bonne nuit",
        "je dois y aller",
        "a+ur",
        "a plus",
        "salut bye",
        "portez-vous bien",
        "adieu",
        "on se revoit bientôt",
        "je file",
    ],
    "remerciement": [
        "merci",
        "merci beaucoup",
        "je te remercie",
        "c'est gentil merci",
        "top merci",
        "merci infiniment",
        "génial merci",
        "c'est super sympa",
        "mille mercis",
        "merci du fond du cœur",
        "c'est trop cool",
        "sympa",
        "merci bien",
        "trop sympa merci",
        "merci pour ton aide",
    ],
    "question_prix": [
        "combien ça coûte",
        "quel est le prix",
        "c'est cher",
        "quel est le tarif",
        "ça coûte combien",
        "quels sont vos prix",
        "c'est payant",
        "c'est gratuit",
        "donne-moi les tarifs",
        "je voudrais connaître les prix",
        "c'est combien",
        "quel est le montant",
        "y a-t-il un coût",
        "tarif de l'abonnement",
        "prix des prestations",
    ],
    "probleme_technique": [
        "ça ne marche pas",
        "j'ai un bug",
        "l'application plante",
        "erreur au démarrage",
        "ça ne fonctionne plus",
        "je n'arrive pas à me connecter",
        "mon compte est bloqué",
        "le site est inaccessible",
        "ça rame",
        "je rencontre un problème technique",
        "écran noir",
        "le logiciel crash",
        "impossible de charger la page",
        "ça freeze",
        "code erreur",
    ],
    "aide": [
        "aide-moi",
        "j'ai besoin d'aide",
        "comment ça marche",
        "je suis perdu",
        "tu peux m'aider",
        "mode d'emploi",
        "explique-moi",
        "je ne comprends rien",
        "SOS",
        "au secours",
        "besoin d'assistance",
        "comment faire",
        "donne-moi un coup de main",
    ],
    "identite": [
        "tu t'appelles comment",
        "c'est quoi ton nom",
        "qui es-tu",
        "tu es qui",
        "quel est ton nom",
        "présente-toi",
        "comment t'appelles-tu",
        "quel est ton prénom",
        "tu es un robot",
        "es-tu une IA",
    ],
    "capacites": [
        "que sais-tu faire",
        "qu'est-ce que tu fais",
        "tu sers à quoi",
        "quelles sont tes compétences",
        "aide-moi à quoi",
        "qu'est-ce que tu peux faire pour moi",
        "quel est ton rôle",
        "tu m'es utile à quoi",
    ],
    "horaires": [
        "quelles sont vos horaires",
        "vous êtes ouverts quand",
        "c'est ouvert le dimanche",
        "à quelle heure vous fermez",
        "vos jours d'ouverture",
        "à quelle heure ça ouvre",
        "c'est ouvert 24h/24",
        "quels sont vos jours de travail",
    ],
    "contact": [
        "comment vous contacter",
        "je veux parler à un humain",
        "donne-moi votre numéro",
        "adresse email",
        "service client",
        "support",
        "joindre quelqu'un",
        "où vous trouver",
        "votre adresse physique",
        "numéro de téléphone",
    ],
    "meteo": [
        "quel temps fait-il",
        "il pleut",
        "il fait beau",
        "quelle est la météo",
        "va-t-il faire chaud",
        "temps aujourd'hui",
    ],
    "blague": [
        "raconte-moi une blague",
        "fais-moi rire",
        "une blague stp",
        "tu connais des blagues",
        "balance une blague",
    ],
}

reponses = {
    "salutation": [
        "Bonjour ! Comment puis-je t'aider aujourd'hui ?",
        "Salut ! Que puis-je faire pour toi ?",
        "Hello ! Ravi de te parler. De quoi as-tu besoin ?",
        "Coucou ! Comment ça va ?",
    ],
    "au_revoir": [
        "Au revoir, à bientôt !",
        "Bonne journée à toi !",
        "Salut, n'hésite pas à revenir si tu as d'autres questions !",
        "Ciao et à la prochaine !",
    ],
    "remerciement": [
        "Avec plaisir !",
        "Je t'en prie ! C'est normal.",
        "Il n'y a pas de quoi ! Content d'avoir pu t'aider.",
        "Avec grand plaisir !",
        "C'est un plaisir de t'aider.",
    ],
    "question_prix": [
        "Les tarifs détaillés sont disponibles sur notre page Prix.",
        "Nos offres s'adaptent à vos besoins. Tu peux consulter notre grille tarifaire en ligne.",
        "Le prix dépend de la formule choisie. Veux-tu le lien vers nos abonnements ?",
        "Nos services proposent différentes gammes de prix selon ce que tu recherches.",
    ],
    "probleme_technique": [
        "Désolé pour ce désagrément. Peux-tu me décrire le bug plus précisément ?",
        "Oups, un souci technique ? Raconte-moi ce qui se passe pour que je puisse t'aiguiller.",
        "Essayez de rafraîchir la page ou de relancer l'application. Si le problème persiste, dis-le-moi !",
        "C'est embêtant ! Dis-moi quel message d'erreur s'affiche pour que l'on règle ça.",
    ],
    "aide": [
        "Je suis là pour ça ! Dis-moi ce qui te pose problème et on règle ça ensemble.",
        "Pas de panique ! Explique-moi ce que tu cherches à faire.",
        "Je peux t'assister pas à pas. Qu'est-ce qui te bloque ?",
    ],
    "identite": [
        "Je suis ton assistant virtuel, conçu pour répondre à tes questions !",
        "On m'appelle ton chatbot préféré. Je n'ai pas de prénom humain, mais je suis là pour t'aider.",
        "Je suis une intelligence artificielle programmée pour te faciliter la vie.",
    ],
    "capacites": [
        "Je peux répondre à tes questions sur nos tarifs, t'aider en cas de souci technique, ou simplement discuter !",
        "Je sais identifier tes intentions pour te guider vers les bonnes informations rapidement.",
        "Je peux t'aider sur plein de sujets liés au service, aux horaires ou résoudre des pannes basiques.",
    ],
    "horaires": [
        "Nos services en ligne sont disponibles 24h/24 et 7j/7. Notre support humain est joignable du lundi au vendredi.",
        "Nous sommes ouverts du lundi au vendredi de 9h à 18h.",
        "Les portes sont ouvertes de 8h à 19h en semaine, et le samedi matin.",
    ],
    "contact": [
        "Tu peux joindre notre support par email à contact@exemple.com ou via notre formulaire en ligne.",
        "Je peux te mettre en relation avec un conseiller si tu le souhaites. Veux-tu que je transmette ton message ?",
        "Notre équipe est joignable au téléphone au 01 23 45 67 89 aux heures d'ouverture.",
    ],
    "meteo": [
        "Je n'ai pas accès aux capteurs météo en temps réel, mais j'espère qu'il fait beau chez toi !",
        "Regarde par la fenêtre, c'est encore le moyen le plus sûr de connaître la météo !",
    ],
    "blague": [
        "Pourquoi les plongeurs plongent-ils toujours en arrière et jamais en avant ? Parce que sinon ils tombent dans le bateau !",
        "C'est l'histoire d'un pinguin qui respire par les fesses. Un jour il s'assoit et il meurt.",
        "Que fait une fraise sur un cheval ? Tagada tagada !",
    ],
    "inconnu": [
        "Je ne suis pas sûr de comprendre, peux-tu reformuler ta phrase ?",
        "Hmm, je n'ai pas bien saisi. Essaie de le dire d'une autre manière ?",
        "Je sèche un peu là... Tu pourrais préciser ta pensée ?",
        "Désolé, mon cerveau de robot bloque un peu sur cette phrase. Peux-tu reformuler ?",
    ],
}